name       : godot
version    : 2.1.2
release    : 7
source     :
    - https://github.com/godotengine/godot/archive/2.1.2-stable.tar.gz : 29b3131449f8ca908be800c4c07020efaa9f90a29b6bc1be8a18a331dc34b49a
license    : MIT
component  : games
summary    : Godot is a fully featured, open source, MIT licensed, game engine.
description: |
    Godot is a fully featured, open source, MIT licensed, game engine.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libwebp)
    - pkgconfig(opusfile)
    - pkgconfig(python-2.7)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - clang
    - scons
build      : |
    GODOT_OPTIONS="use_llvm=yes bits=64 deprecated=no builtin_enet=no builtin_freetype=no builtin_glew=no builtin_libogg=no builtin_libpng=no builtin_libtheora=no builtin_libvpx=no builtin_libwebp=no builtin_openssl=no builtin_opus=no builtin_zlib=no"
    # IDE
    scons %JOBS% platform=x11 tools=yes $GODOT_OPTIONS target=release_debug
    # Linux X11 64 Template
    scons %JOBS% platform=x11 tools=no $GODOT_OPTIONS target=release
install    : |
    install -D -m 00755 bin/godot.x11.opt.tools.64.llvm $installdir/usr/bin/godot
    install -D -m 00755 bin/godot.x11.opt.64.llvm $installdir/usr/share/godot/templates/linux_x11_64_release

    install -D -m 00644 icon.png $installdir/usr/share/pixmaps/godot.png
    install -D -m 00644 $pkgfiles/godot.desktop $installdir/usr/share/applications/godot.desktop
