name       : godot
version    : 2.1.5
release    : 12
source     :
    - https://github.com/godotengine/godot/archive/2.1.5-stable.tar.gz : 74179c08bcc20cc89b4ac2785a31f201d81eb4aa875c80ffcb82d9fb80e8e187
license    :
    - CC-BY-3.0
    - MIT
component  : games
summary    : Godot is a fully featured, open source, MIT licensed, game engine
description: |
    Godot Engine is a feature-packed, cross-platform game engine to create 2D and 3D games from a unified interface. It provides a comprehensive set of common tools, so that users can focus on making games without having to reinvent the wheel. Games can be exported in one click to a number of platforms, including the major desktop platforms (Linux, Mac OSX, Windows) as well as mobile (Android, iOS) and web-based (HTML5) platforms.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libwebp)
    - pkgconfig(opusfile)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - llvm-clang
    - scons
build      : |
    GODOT_OPTIONS="use_llvm=yes bits=64 deprecated=no builtin_enet=no builtin_freetype=no builtin_glew=no builtin_libogg=no builtin_libpng=no builtin_libtheora=no builtin_libvpx=no builtin_libwebp=no builtin_openssl=no builtin_opus=no builtin_zlib=no udev=yes"
    # IDE
    scons %JOBS% platform=x11 tools=yes $GODOT_OPTIONS target=release_debug
    # Linux X11 64 Template
    scons %JOBS% platform=x11 tools=no $GODOT_OPTIONS target=release
install    : |
    install -D -m 00755 bin/godot.x11.opt.tools.64.llvm $installdir/usr/bin/godot
    install -D -m 00755 bin/godot.x11.opt.64.llvm $installdir/usr/share/godot/templates/linux_x11_64_release

    install -D -m 00644 icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/godot.svg
    install -D -m 00644 icon.png $installdir/usr/share/pixmaps/godot.png
    install -D -m 00644 $pkgfiles/godot.desktop $installdir/usr/share/applications/godot.desktop
    install -D -m 00644 misc/dist/linux/godot.6 installdir/usr/share/man/man6/godot.6
    install -D -m 00644 misc/dist/linux/godot.appdata.xml $installdir/usr/share/metainfo/godot.appdata.xml
