name       : godot
version    : 2.1
release    : 3
source     :
    - https://github.com/godotengine/godot/archive/2.1-stable.tar.gz : 0d2a6f5a3689a818cb4859e7655e64a4d603940fae1bdf16a18b980c22b0b6fe
license    : MIT
component  : games
summary    : Godot is a fully featured, open source, MIT licensed, game engine.
description: |
    Godot is a fully featured, open source, MIT licensed, game engine.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpulse)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - scons
build      : |
    # IDE
    scons %JOBS% platform=x11 tools=yes target=release_debug bits=64
    # Headless server for builds
    scons %JOBS% platform=server tools=no target=release bits=64
    # Linux X11 64 Template
    scons %JOBS% platform=x11 tools=no target=release bits=64
install    : |
    install -D -m 00755 bin/godot.x11.opt.tools.64 $installdir/usr/bin/godot
    install -D -m 00755 bin/godot_server.server.opt.64 $installdir/usr/bin/godot-headless
    install -D -m 00755 bin/godot.x11.opt.64 $installdir/usr/share/godot/templates/linux_x11_64_release

    install -D -m 00644 icon.png $installdir/usr/share/pixmaps/godot.png
    install -D -m 00644 $pkgfiles/godot.desktop $installdir/usr/share/applications/godot.desktop
