name       : godot
version    : 2.0.4.1
release    : 1
source     :
    - https://github.com/godotengine/godot/archive/2.0.4.1-stable.tar.gz : 7dc2a012740bef6ac1948e05a4bc9a21700af2dc861d963bbf1235fd93efadc9
license    : MIT
component  : games
summary    : Godot is a fully featured, open source, MIT licensed, game engine.
description: |
    Godot is a fully featured, open source, MIT licensed, game engine.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libpulse)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - scons
build      : |
    scons %JOBS% platform=x11 tools=yes
install    : |
    install -D -m 00755 bin/godot.x11.tools.64 $installdir/usr/bin/godot

    install -D -m 00644 icon.png $installdir/usr/share/pixmaps/godot.png
    install -D -m 00644 $pkgfiles/godot.desktop $installdir/usr/share/applications/godot.desktop
