name       : godot
version    : 3.0.6
release    : 16
source     :
    - https://github.com/godotengine/godot/archive/3.0.6-stable.tar.gz : 50431e021ee5ec21002cc23435f530f8fde518c6eb7085c9f7f1027abaae2581
license    :
    - CC-BY-3.0
    - MIT
component  : games
summary    : Godot is a fully featured, open source, MIT licensed, game engine
description: |
    Godot Engine is a feature-packed, cross-platform game engine to create 2D and 3D games from a unified interface. It provides a comprehensive set of common tools, so that users can focus on making games without having to reinvent the wheel. Games can be exported in one click to a number of platforms, including the major desktop platforms (Linux, Mac OSX, Windows) as well as mobile (Android, iOS) and web-based (HTML5) platforms.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libenet)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libwebp)
    - pkgconfig(mono)
    - pkgconfig(opusfile)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - llvm-clang
    - scons
    - xorg-server-xvfb
    - yasm
build      : |
    # bullet: requires v2.88 which hasn't been released yet
    # xbuild_fallback: until msbuild lands in the repository
    GODOT_OPTIONS="use_llvm=yes bits=64 deprecated=no builtin_enet=no builtin_freetype=no builtin_bullet=yes builtin_libogg=no builtin_libpng=no builtin_libtheora=no builtin_libvpx=no builtin_libwebp=no builtin_openssl=no builtin_opus=no builtin_zlib=no builtin_pcre2=no udev=yes module_mono_enabled=yes xbuild_fallback=yes"

    # Build temporary binary to compile with mono
    scons %JOBS% platform=x11 tools=yes use_llvm=yes module_mono_enabled=yes mono_glue=no xbuild_fallback=yes
    # Generate glue sources
    xvfb-run -a -s "-screen 0 1024x768x24" bin/godot.x11.tools.64.llvm.mono --generate-mono-glue modules/mono/glue

    # IDE
    scons %JOBS% platform=x11 tools=yes $GODOT_OPTIONS target=release_debug
    # Linux X11 64 Template
    scons %JOBS% platform=x11 tools=no $GODOT_OPTIONS target=release
install    : |
    install -D -m 00755 bin/godot.x11.opt.* -t $installdir/%libdir%/godot
    install -m 00644 bin/*.dll -t $installdir/%libdir%/godot
    install -D -m 00644 icon.svg $installdir/%PREFIX%/share/icons/hicolor/scalable/apps/godot.svg
    install -D -m 00644 icon.png $installdir/%PREFIX%/share/pixmaps/godot.png
    install -D -m 00644 misc/dist/linux/godot.desktop $installdir/%PREFIX%/share/applications/godot.desktop
    install -D -m 00644 misc/dist/linux/godot.6 $installdir/%PREFIX%/share/man/man6/godot.6
    install -D -m 00644 misc/dist/linux/godot.appdata.xml $installdir/%PREFIX%/share/metainfo/godot.appdata.xml
    install -d -m 00755 $installdir/%PREFIX%/bin
    ln -s %libdir%/godot/godot.x11.opt.tools.64.llvm.mono $installdir/%PREFIX%/bin/godot
